### PR TITLE
update cpu variant

### PR DESCRIPTION
**Pull request by mosimchah**
Hisilicon Kirin 970 has 4 core cortex-a73 &
 4 core cortex-a53 use cortex-a73 as well

Change-Id: I7d96a66d9ddd1cc2f20baf3e58707a68e8768a83

### CODE REVIEW

**Comment by mosimchah** [comment]
tested on berkeley with no issues so far

**Comment by luk1337** [comment]
You want to optimize for the worst cores in the system. Optimizing for A73 will only make A53 cores perform worse.

**Comment by luk1337** [comment]
Also funfact, not even our configuration is right. I believe that they use A15 optimizations on stock.

**Comment by mosimchah** [comment]
Oh good to know

**Pull request closed without merging**
